TekiBlog/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TekiBlog.ViewModels;
using BusinessObjects;
using Microsoft.Extensions.Logging;
using ActionServices;
using ValidationUtilities;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;
using Microsoft.Extensions.Configuration;

namespace TekiBlog.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<ArticleController> _logger;
        private readonly IService _service;
        private readonly IGenericValidationUtil<CreateArticleViewModel> _validation;

        public ArticleController(IConfiguration configuration, 
            UserManager<ApplicationUser> userManager,
            ILogger<ArticleController> logger,
            IService service,
            IGenericValidationUtil<CreateArticleViewModel> validation)
        {
            _configuration = configuration;
            _userManager = userManager;
            _logger = logger;
            _service = service;
            _validation = validation;
        }

        public async Task<IActionResult> Home(int? pageNumber, int? tagid)
        {
            _logger.LogInformation("Article home is called");
            IQueryable<Article> articles = null;
            if (tagid != null || tagid >= 1)
            {
                articles = _service.GetArticleByTag(tagid ?? 1);
                ViewData["TagHeader"] = _service.GetTagByID((int)tagid).Name;
            }
            else
            {
                articles = _service.GetArticleByStatus("Active");
            }

            foreach (var a in articles)
            {
                _logger.LogInformation($"Article {a.ID} : {a.ArticleTags.Count}");
                foreach (var at in a.ArticleTags)
                {
                    _logger.LogInformation($"Tag {at.TagId}");
                    _logger.LogInformation($"Tag {at.Tag.Name}");
                }
            }
            _logger.LogInformation("--------------------------------");
            int pageSize = PaginatedList<Article>.PerPage;

            PaginatedList<Article> result = await PaginatedList<Article>.CreateAsync(articles, pageNumber ?? 1, pageSize);

            _logger.LogInformation("result size : " + result.Count());
            foreach (var a in result)
            {
                _logger.LogInformation($"Article {a.ID} : {a.ArticleTags.Count}");
                foreach (var at in a.ArticleTags)
                {
                    _logger.LogInformation($"Tag {at.TagId}");
                    _logger.LogInformation($"Tag {at.Tag}");
                }
            }
            HomePageViewModel viewModel = new HomePageViewModel
            {
                Articles = result,
            };

            var user = await _userManager.GetUserAsync(User);
            if (user?.Id != null)
            {
                List<Bookmark> bookmarks = await _service.GetBookmarks(user).ToListAsync();
                viewModel.UserBookmarks = bookmarks;
            }


            return View(viewModel);

        }

        [HttpGet]
        public async Task<IActionResult> Detail(Guid id)
        {
            if (id == null)
            {
                _logger.LogInformation("article id is null");
                return NotFound();
            }

            var article = _service.GetArticle(id);
            if (article == null)
            {
                _logger.LogInformation($"request for article {id} returned null");
                return NotFound();
            }
            else
            {
                _logger.LogInformation($"status of article {article.ID}: {article.Status.Name}");
                var user = await _userManager.GetUserAsync(User);
                if (user == null || !article.User.Equals(user))
                {
                    _logger.LogInformation($"user {user} called for article {id}");
                    if (!article.Status.Name.Equals("Active"))
                    {
                        return NotFound();
                    }
                }
                else
                {
                    _logger.LogInformation("user is authorized");
                    if (article.Status.Name.Equals("Deleted"))
                    {
                        return NotFound();
                    }
                }
            }

            _logger.LogInformation($"user receives article {article.ID}");

            return View(article);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> Editor(Guid id)
        {
            #region setup validaiton viewdata
            ViewData["SummaryMaxLen"] = _validation.GetMaxLen("Summary");
            ViewData["SummaryMinLen"] = _validation.GetMinLen("Summary");

            ViewData["TitleMaxLen"] = _validation.GetMaxLen("Title");
            ViewData["TitleMinLen"] = _validation.GetMinLen("Title");

            ViewData["ContentMaxLen"] = _validation.GetMaxLen("ArticleRaw");
            ViewData["ContentMinLen"] = _validation.GetMinLen("ArticleRaw");
            #endregion

            if (id != null)
            {
                var article = _service.GetArticle(id);
                if (article != null)
                {
                    var user = await _userManager.GetUserAsync(User);
                    if (article.User.Id.Equals(user?.Id))
                    {
                        return View(new CreateArticleViewModel
                        {
                            Id = article.ID,
                            ArticleContent = article.ContentHtml,
                            Title = article.Title,
                            Summary = article.Summary,
                            Status = article.Status,
                            CoverImage = article.CoverImage,
                            ArticleTags = article.ArticleTags
                        });
                    }
                }
            }

            return View();
        }

        //[HttpPost]
        //public string AjaxTest(CreateArticleViewModel article)
        //{
        //    string received = article.ArticleContent;

        //    Console.Write(received);

        //    return received;
        //}

        [HttpPost]
        [Authorize(Roles = "User")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostArticle(CreateArticleViewModel article)
        {
            try
            {
                int iW = _configuration.GetValue<int>("Article:Image:Width");
                int iH = _configuration.GetValue<int>("Article:Image:Height");
                int tW = _configuration.GetValue<int>("Article:Thumbnail:Width");
                int tH = _configuration.GetValue<int>("Article:Thumbnail:Height");

                _service.GetImage(out byte[] articleImage, this.Request);

                articleImage = _service.ResizeImgageByWidth(articleImage, iW, ImageFormat.Jpeg);
                article.CoverImage = _service.CropImage(articleImage, new Rectangle(0, 0, iW, iH), ImageFormat.Jpeg);
                //article.ThumbnailImage = _service.CropImage(articleImage, new Rectangle(tW / 3, 0, tW, tH), ImageFormat.Jpeg);
                article.ThumbnailImage = _service.ResizeImgageByWidth(article.CoverImage, tW, ImageFormat.Jpeg);
            }
            catch
            {
                _logger.LogInformation("failed to retrieve image");
            }

            string statusType = (ModelState.IsValid) ? "Active" : "Draft";

            var user = await _userManager.GetUserAsync(User);

            // Get status for this post
            Status status = _service.GetStatus(statusType);

            string html = article.ArticleContent;

            string raw = article.ArticleRaw;

            DateTime publishDate = ( ModelState.IsValid ) ? DateTime.UtcNow : DateTime.MinValue;
            // Create article model to insert to Database
            Article articleModel = new Article
            {
                Title = article.Title?.Trim(),
                Summary = article.Summary?.Trim(),
                DatePosted = publishDate,
                LastUpdate = DateTime.UtcNow,
                ContentHtml = html,
                ContentRaw = raw?.Trim(),
                Status = status,
                CoverImage = article.CoverImage,
                ThumbnailImage = article.ThumbnailImage,
                User = user
            };

            List<int> tagList = _service.StringToInt(article?.TagsString?.Split(",")?.ToList());

            _service.AddArticle(articleModel);
            _service.AddArticleTag(articleModel.ID, tagList);

            if (await _service.Commit())
            {
                //bool uploadValid;

                //try
                //{
                //    string tB = _configuration.GetValue<string>("Credentials:AWS:ThumbnailBucket");
                //    string iB = _configuration.GetValue<string>("Credentials:AWS:ImageBucket");
                //    string addr = _configuration.GetValue<string>("Credentials:AWS:CredentialAddress");

                //    string k = $"{_configuration.GetValue<string>("Credentials:AWS:k1")}{_configuration.GetValue<string>("Credentials:AWS:k2")}{_configuration.GetValue<string>("Credentials:AWS:k3")}";
                //    string sK = $"{_configuration.GetValue<string>("Credentials:AWS:k4")}{_configuration.GetValue<string>("Credentials:AWS:k5")}{_configuration.GetValue<string>("Credentials:AWS:k6")}";

                //    await _service.UploadToS3(k, sK, iB, article.CoverImage, $"{articleModel.ID}");

TekiBlog/Controllers/BookmarkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ActionServices;
using BusinessObjects;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TekiBlog.ViewModels;

namespace TekiBlog.Controllers
{
    public class BookmarkController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<ArticleController> _logger;
        private readonly IService _service;

        public BookmarkController(UserManager<ApplicationUser> userManager,
            ILogger<ArticleController> logger,
            IService service)
        {
            _userManager = userManager;
            _logger = logger;
            _service = service;
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> BookmarkAdd(Guid id)
        {
            var user = await _userManager.GetUserAsync(User);
            bool hasError;
            try
            {
                Bookmark bookmark = new Bookmark
                {
                    UserID = user.Id,
                    ArticleID = id,
                    DatePosted = DateTime.UtcNow
                };
    
                _service.AddBookmark(bookmark);
                hasError = !(await _service.Commit());
            }
            catch
            {
                _logger.LogInformation($"failed to book mark article {id}");
                hasError = true;
            }

            if(hasError)
                return Ok("error");
            else
                return Ok(0);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> UserBookmark()
        {
            var user = await _userManager.GetUserAsync(User);
            BookmarkViewModel viewModel = new BookmarkViewModel { Bookmarks = _service.GetBookmarks(user, true)};
            return View(viewModel);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> BookmarkRemove(Guid id)
        {
            var user = await _userManager.GetUserAsync(User);
            bool hasError;
            try
            {
                Bookmark bookmark = new Bookmark
                {
                    UserID = user.Id,
                    ArticleID = id,
                    DatePosted = DateTime.UtcNow
                };

                _service.RemoveBookmark(bookmark);
                hasError = !( await _service.Commit() );
            }
            catch
            {
                _logger.LogInformation($"failed to remove bookmark of article {id}");
                hasError = true;
            }

            if (hasError)
                return Ok("error");
            else
                return Ok(1);
        }
    }
}

TekiBlog/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ActionServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace TekiBlog.Controllers
{
    public class TagController : Controller
    {
        private readonly ILogger<TagController> _logger;
        private readonly IService _service;

        public TagController(ILogger<TagController> logger,
            IService service)
        {
            _service = service;
            _logger = logger;
        }
        public IActionResult Index(int? id)
        {
            return View();
        }

        [HttpGet]
        public JsonResult Get()
        {
            var tags = _service.GetAllActiveTags();
            var result = new List<Object>();
            foreach( var tag in tags)
            {
                var tagJson = new
                {
                    value = tag.Id,
                    text = tag.Name,
                    continent = "tag"
                };
                result.Add(tagJson);
            }
            return Json(result);
        }
    }
}

TekiBlog/Views/Shared/_ComposePartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager;
@inject UserManager<ApplicationUser> UserManager;


@if (SignInManager.IsSignedIn(User))
{
    var user = await UserManager.GetUserAsync(User);
    //var role = await UserManager
    var role = await UserManager.GetRolesAsync(user);
    if (role.Contains("User"))
    {
        <div class="btn-compose-container">
            <a id="btn-compose">
                <span class="circle">
                    <div class="loader-compose d-none"></div>
                    <div class="vertical"></div>
                    <div class="horizontal"></div>
                </span>
            </a>
        </div>
    }
}

TekiBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Teki</title>
    <link rel="icon" href="~/favicon.png" sizes="32x32" type="image/png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    @RenderSection("PreScripts", required: false)
    @RenderSection("Styles", required: false)
</head>
<body>
    <header id="site-header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white mb-3">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img class="img-brand" src="~/img/logo.png">
            </a>
            <partial name="_UserLinkPartial" />

            <ul class="navbar-nav mr-auto"></ul>

            <form asp-controller="Article" class="form-inline my-2 my-lg-0" asp-action="Search" method="get">
                <input class="form-control mr-sm-2" type="text" placeholder="Input here..." name="searchValue" aria-label="Search" value="@ViewData["SearchValue"]">
                <button class="btn btn-outline-secondary my-2 my-sm-0" title="Search" type="submit"><i class="fa fa-search"></i></button>

            </form>

            <partial name="_LoginPartial" />

        </nav>
    </header>
    @RenderSection("MidBody", required: false)
    @RenderSection("CoverImg", required: false)
<div class="container body-content">
    <div id="modal-container"></div>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Teki - <a href="#">Project Report</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TekiBlog/Views/Shared/_ManageNav.cshtml
<ul class="nav nav-pills flex-column">
    <li class="nav-item" id="blog-nav">
        <a class="nav-link" asp-controller="Admin" asp-action="Index">Manage Blog</a>
    </li>
    <li class="nav-item" id="user-nav">
        <a class="nav-link" asp-controller="Admin" asp-action="ViewUser">Manage User</a>
    </li>
    <li class="nav-item" id="tag-nav">
        <a class="nav-link" asp-controller="Admin" asp-action="Tag">Manage Tag</a>
    </li>
</ul>

TekiBlog/Views/Shared/_NotificationPartial.cshtml
<div id="page-notification" class="toast toast-hide" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <strong class="mr-auto"><i class="fa fa-bell"></i> Notification</strong>
    </div>
    <div id="page-notification-body" class="toast-body">
        Hello, world! This is a toast message.
    </div>
</div>

TekiBlog/Views/Shared/_Tags.cshtml
@inject ActionServices.IService service;

<div>
    @{
        var tags = service.GetAllActiveTags().OrderBy(a => a.Name);
        if (tags.Count() != 0)
        {
            foreach (var tag in tags)
            {
                <a class="tag badge" asp-controller="Article" asp-action="Home" asp-route-tagid="@tag.Id">
                    @tag.Name
                </a>
            }
        }
    }
</div>

TekiBlog/Views/Shared/_UserDraftListPartial.cshtml
@model TekiBlog.ViewModels.UserDraftsViewModel

<div id="draft-modal" class="modal fade show" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa fa-pencil-square"></i> Your Drafts</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Title</th>
                            <th scope="col">Last Updated</th>
                        </tr>
                    </thead>
                    <tbody class="draft-tbody">
                        @foreach (Article article in Model.UserDrafts)
                        {
                        <tr editor-id="@article.ID" class="draft-row">
                            @if (article.Title == null)
                            {
                                <td class="empty">Untitled Article</td>
                            }
                            else
                            {
                                <td>@article.Title</td>
                            }
                            <td>@article.LastUpdate</td>
                        </tr>
                        }
                        <tr class="draft-row">
                            <td colspan="2">New Article...</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline" data-dismiss="modal">Close</button>
                <form asp-controller="Article" asp-action="Editor">
                    <input id="editor-id" type="hidden" name="id"/>
                    <input type="submit" class="btn btn-primary" value="Accept"/>
                </form>
            </div>
        </div>
    </div>
</div>

TekiBlog/Views/Shared/_UserLinkPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using BusinessObjects
@inject SignInManager<ApplicationUser> SignInManager;
@inject UserManager<ApplicationUser> UserManager;

@if (SignInManager.IsSignedIn(User))
{
    var user = await UserManager.GetUserAsync(User);
    //var role = await UserManager
    var role = await UserManager.GetRolesAsync(user);
    if (role.Contains("Admin"))
    {
        if (role.Contains("User"))
        {
            <div class="dropdown">
                @*<div>Hello</div>*@
                <button class="btn btn-secondary dropdown-toggle nav-item btn btn-outline-secondary btn-outline my-2 my-sm-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @user.FirstName @user.LastName
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Index">Admin page</a>
                    <a class="dropdown-item" asp-controller="Profile" asp-action="Index">Your Page</a>
                    <a class="dropdown-item" asp-controller="Bookmark" asp-action="UserBookmark">My Bookmarks</a>
                    <a class="dropdown-item" asp-controller="Profile" asp-action="Info">Edit Your Profile</a>
                    <a class="dropdown-item" asp-controller="Profile" asp-action="ChangePassword">Change password</a>
                </div>

                @*<a class="" asp-area="" asp-controller="Profile" asp-action="Index" title="Manage">@user.FirstName @user.LastName</a>*@
            </div>
        }
        else
        {
            <a class=" nav-item btn btn-outline-secondary btn-outline my-2 my-sm-0" asp-area="" asp-controller="Admin" asp-action="Index">@user.FirstName @user.LastName</a>
        }
    }
    else
    {
        <div class="dropdown">
            @*<div>Hello</div>*@
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @user.FirstName @user.LastName
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" asp-controller="Profile" asp-action="Index">Your Page</a>
                <a class="dropdown-item" asp-controller="Bookmark" asp-action="UserBookmark">My Bookmarks</a>
                <a class="dropdown-item" asp-controller="Profile" asp-action="Info">Edit Your Profile</a>
                <a class="dropdown-item" asp-controller="Profile" asp-action="ChangePassword">Change password</a>
            </div>

            @*<a class="" asp-area="" asp-controller="Profile" asp-action="Index" title="Manage">@user.FirstName @user.LastName</a>*@
        </div>
    }
}